all: my-cat my-grep my-zip my-unzip

my-cat: my-cat.c
	gcc -g -o my-cat my-cat.c -Wall -Werror

my-grep: my-grep.c
	gcc -g -o my-grep my-grep.c -Wall -Werror
my-zip: my-zip.c
	gcc -g -o my-zip my-zip.c -Wall -Werror
my-unzip: my-unzip.c
	gcc -g -o my-unzip my-unzip.c -Wall -Werror 
